disabled_rules: # Default Rules에서 비활성화할 규칙
    
    # 라인 뒤에 공백이 없어야 합니다. https://realm.github.io/SwiftLint/trailing_whitespace.html
    - trailing_whitespace
    
    # 변수와 타입의 이름 길이를 제한합니다.
    - identifier_name
    - type_name
    
opt_in_rules:
  # .count==0 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_count.html
  - empty_count
  
  # 빈 String 문자열과 비교하는 것 보다는 .isEmpty를 사용하는 것이 좋습니다. https://realm.github.io/SwiftLint/empty_string.html
  - empty_string

excluded: # SwiftLint 검사에서 제외할 파일 경로
  - Pods
  - voyager/AppDelegate.swift
  - voyager/SceneDelegate.swift

# 규칙별 세부 설정 #

line_length: # 한 줄의 길이를 제한합니다.
  warning: 120
  ignores_comments: true

force_cast: warning # as! 의 사용을 제한합니다.
